version: "3.7"
services:
  server:
    build: .
    container_name: jelly-party-server
    environment:
      - NODE_ENV=development
    ports:
      - "8080:8080" # nodejs websocket server
    volumes:
      - type: bind # certificate renewal doesn't require rebuilding the image
        source: /etc/letsencrypt
        target: /etc/letsencrypt
      - type: volume
        source: log_volume
        target: /var/log/serverlog
    restart: unless-stopped
    network_mode: "host"
  filebeat:
    build: ./filebeat
    container_name: filebeat
    env_file:
      - beat.env
    volumes:
      - type: volume
        source: log_volume
        target: /log_volume
    depends_on:
      - server
    network_mode: "host"
    command: ["./wait-for-it.sh", "localhost:8081", "--", "filebeat", "-environment", "container"]
  metricbeat:
    build: ./metricbeat
    container_name: metricbeat
    env_file:
      - beat.env
    volumes:
      - type: volume
        source: log_volume
        target: /log_volume
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /proc
        target: /hostfs/proc
        read_only: true
      - type: bind
        source: /sys/fs/cgroup
        target: /hostfs/sys/fs/cgroup
        read_only: true
      - type: bind
        source: /
        target: /hostfs
        read_only: true
    network_mode: "host"
    environment:
      system.hostfs: /hostfs
    user: root
    cap_add:
      - sys_ptrace
      - dac_read_search
    depends_on:
      - server
volumes:
  log_volume:
