version: "3.7"
services:
  jelly-server:
    environment:
      - MODE=production
  filebeat:
    build: ./filebeat
    container_name: filebeat
    env_file: beat.env
    volumes:
      - type: volume
        source: log_volume
        target: /log_volume
    depends_on:
      - jelly-server
    network_mode: "host"
    command:
      [
        "./wait-for-it.sh",
        "jelly-server:8081",
        "--",
        "filebeat",
        "-environment",
        "container",
      ]
