version: "3.7"
services:
  jelly-server:
    build: .
    container_name: jelly-party-server
    environment:
      - MODE=development
    expose:
      - 8080
    volumes:
      - type: volume
        source: log_volume
        target: /var/log/serverlog
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.jelly-router.entrypoints=wssecure
      - traefik.http.routers.jelly-router.rule=Host(`wss.jelly-party.com`)
      - traefik.http.routers.jelly-router.tls=true
      - traefik.http.routers.jelly-router.tls.certresolver=myresolver
  traefik:
    image: traefik:v2.9
    restart: always
    depends_on:
      - jelly-server
    command:
      #- "--log.level=DEBUG"
      # - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.wssecure.address=:8080"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=hi@jelly-party.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
volumes:
  log_volume:
