version: "3.7"
services:
  server:
    build: .
    container_name: jelly-party-server
    environment:
      - NODE_ENV=development
    env_file: staging.env
    ports:
      - "8080:8080" # nodejs websocket server
    volumes:
      - type: bind # certificate renewal doesn't require rebuilding the image
        source: /etc/letsencrypt
        target: /etc/letsencrypt
      - type: volume
        source: log_volume
        target: /var/log/serverlog
    restart: unless-stopped
    network_mode: "host"
volumes:
  log_volume:
