version: "3.7"
services:
  jelly-server:
    build: .
    container_name: jelly-party-server
    environment:
      - MODE=development
    expose:
      - 8080
    volumes:
      - type: volume
        source: log_volume
        target: /var/log/serverlog
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.jelly-router.entrypoints=wssecure
      - traefik.http.routers.jelly-router.rule=Host(`wss.jelly-party.com`)
      - traefik.http.routers.jelly-router.tls=true
      - traefik.http.routers.jelly-router.tls.certresolver=leresolver
  traefik:
    image: traefik:v2.8.1
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    restart: always
    depends_on:
      - jelly-server
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
volumes:
  log_volume:
