providers:
  docker:
    watch: true
    exposedByDefault: false
entryPoints:
  web:
    http:
      redirections:
        entryPoint:
          to: wssecure
          scheme: https
  wssecure:
    address: :8080
certificatesResolvers:
  leresolver:
    acme:
      email: hi@jelly-party.com
      storage: acme.json
      httpChallenge:
        entryPoint: web
